BEGIN;
CREATE TABLE IF NOT EXISTS roles(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE,active BOOLEAN NOT NULL DEFAULT TRUE);
ALTER TABLE users ADD COLUMN IF NOT EXISTS availability_status TEXT DEFAULT 'Active';
CREATE INDEX IF NOT EXISTS users_availability_idx ON users(availability_status);
INSERT INTO roles(name) VALUES ('Project Manager'),('Product Owner'),('Business Analyst'),('Developer'),('Tester'),('UX/UI'),('Data Analyst') ON CONFLICT(name) DO NOTHING;
COMMIT;
