-- ============================================================
-- v59 SAFE MIGRATION (Supabase / PostgreSQL)
-- ⚠️ ADDITIVE เท่านั้น — ไม่มี DROP / DELETE / TRUNCATE → ข้อมูลเดิมไม่หาย
-- รันใน Supabase SQL Editor: วางทั้งไฟล์ → Run (รันซ้ำได้ idempotent)
-- ============================================================
BEGIN;

-- 1) Actual dates ของ Task (สำหรับ Gantt Actual bar + ช่องกรอกใน Task Drawer)
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS actual_start_date BIGINT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS actual_end_date   BIGINT;

-- 2) Project Category (ติดได้หลาย Category ต่อ 1 Project)
CREATE TABLE IF NOT EXISTS project_category_tags (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL,
  category   TEXT   NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS project_category_tags_uniq ON project_category_tags(project_id, category);
CREATE INDEX IF NOT EXISTS project_category_tags_project_idx ON project_category_tags(project_id);

COMMIT;

-- ตรวจสอบ (ควรเห็นคอลัมน์ actual_start_date, actual_end_date และตาราง project_category_tags)
-- SELECT column_name FROM information_schema.columns WHERE table_name='tasks' AND column_name LIKE 'actual_%';
-- SELECT to_regclass('public.project_category_tags');
