-- V64 COMBINED SAFE MIGRATION (run once in Supabase SQL Editor)
-- Additive/idempotent: no existing rows are deleted.
BEGIN;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS actual_start_date BIGINT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS actual_end_date BIGINT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS gantt_health TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS actual_progress NUMERIC(5,2) DEFAULT 0;
CREATE TABLE IF NOT EXISTS project_category_tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL,
  category TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS project_category_tags_uniq ON project_category_tags(project_id,category);
CREATE INDEX IF NOT EXISTS project_category_tags_project_idx ON project_category_tags(project_id);
ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_gantt_health_check;
ALTER TABLE tasks ADD CONSTRAINT tasks_gantt_health_check CHECK (gantt_health IS NULL OR gantt_health IN ('green','yellow','red'));
ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_actual_progress_check;
ALTER TABLE tasks ADD CONSTRAINT tasks_actual_progress_check CHECK (actual_progress IS NULL OR (actual_progress>=0 AND actual_progress<=100));
COMMIT;
